# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sri/hermes3d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sri/hermes3d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/sri/hermes3d/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sri/hermes3d/CMakeFiles /home/sri/hermes3d/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sri/hermes3d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named benchmarks

# Build rule for target.
benchmarks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmarks
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	$(MAKE) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) -f CMakeFiles/examples.dir/build.make CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named test-quick

# Build rule for target.
test-quick: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-quick
.PHONY : test-quick

# fast build rule for target.
test-quick/fast:
	$(MAKE) -f CMakeFiles/test-quick.dir/build.make CMakeFiles/test-quick.dir/build
.PHONY : test-quick/fast

#=============================================================================
<<<<<<< HEAD
# Target rules for targets named hermes3d-cplx-debug

# Build rule for target.
hermes3d-cplx-debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hermes3d-cplx-debug
.PHONY : hermes3d-cplx-debug

# fast build rule for target.
hermes3d-cplx-debug/fast:
	$(MAKE) -f src/CMakeFiles/hermes3d-cplx-debug.dir/build.make src/CMakeFiles/hermes3d-cplx-debug.dir/build
.PHONY : hermes3d-cplx-debug/fast

#=============================================================================
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
# Target rules for targets named hermes3d-debug

# Build rule for target.
hermes3d-debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hermes3d-debug
.PHONY : hermes3d-debug

# fast build rule for target.
hermes3d-debug/fast:
	$(MAKE) -f src/CMakeFiles/hermes3d-debug.dir/build.make src/CMakeFiles/hermes3d-debug.dir/build
.PHONY : hermes3d-debug/fast

#=============================================================================
# Target rules for targets named adapt-h1-simple

# Build rule for target.
adapt-h1-simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adapt-h1-simple
.PHONY : adapt-h1-simple

# fast build rule for target.
adapt-h1-simple/fast:
	$(MAKE) -f tests/adapt/h1-simple/CMakeFiles/adapt-h1-simple.dir/build.make tests/adapt/h1-simple/CMakeFiles/adapt-h1-simple.dir/build
.PHONY : adapt-h1-simple/fast

#=============================================================================
# Target rules for targets named projection

# Build rule for target.
projection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projection
.PHONY : projection

# fast build rule for target.
projection/fast:
	$(MAKE) -f tests/adapt/projection/CMakeFiles/projection.dir/build.make tests/adapt/projection/CMakeFiles/projection.dir/build
.PHONY : projection/fast

#=============================================================================
# Target rules for targets named adapt-smooth

# Build rule for target.
adapt-smooth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adapt-smooth
.PHONY : adapt-smooth

# fast build rule for target.
adapt-smooth/fast:
	$(MAKE) -f tests/adapt/smooth/CMakeFiles/adapt-smooth.dir/build.make tests/adapt/smooth/CMakeFiles/adapt-smooth.dir/build
.PHONY : adapt-smooth/fast

#=============================================================================
# Target rules for targets named calc-tetra-h1

# Build rule for target.
calc-tetra-h1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-tetra-h1
.PHONY : calc-tetra-h1

# fast build rule for target.
calc-tetra-h1/fast:
	$(MAKE) -f tests/calc/tetra-h1/CMakeFiles/calc-tetra-h1.dir/build.make tests/calc/tetra-h1/CMakeFiles/calc-tetra-h1.dir/build
.PHONY : calc-tetra-h1/fast

#=============================================================================
# Target rules for targets named calc-tetra-h1-dirichlet

# Build rule for target.
calc-tetra-h1-dirichlet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-tetra-h1-dirichlet
.PHONY : calc-tetra-h1-dirichlet

# fast build rule for target.
calc-tetra-h1-dirichlet/fast:
	$(MAKE) -f tests/calc/tetra-h1-dirichlet/CMakeFiles/calc-tetra-h1-dirichlet.dir/build.make tests/calc/tetra-h1-dirichlet/CMakeFiles/calc-tetra-h1-dirichlet.dir/build
.PHONY : calc-tetra-h1-dirichlet/fast

#=============================================================================
# Target rules for targets named calc-tetra-h1-neumann

# Build rule for target.
calc-tetra-h1-neumann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-tetra-h1-neumann
.PHONY : calc-tetra-h1-neumann

# fast build rule for target.
calc-tetra-h1-neumann/fast:
	$(MAKE) -f tests/calc/tetra-h1-neumann/CMakeFiles/calc-tetra-h1-neumann.dir/build.make tests/calc/tetra-h1-neumann/CMakeFiles/calc-tetra-h1-neumann.dir/build
.PHONY : calc-tetra-h1-neumann/fast

#=============================================================================
# Target rules for targets named calc-tetra-h1-newton

# Build rule for target.
calc-tetra-h1-newton: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-tetra-h1-newton
.PHONY : calc-tetra-h1-newton

# fast build rule for target.
calc-tetra-h1-newton/fast:
	$(MAKE) -f tests/calc/tetra-h1-newton/CMakeFiles/calc-tetra-h1-newton.dir/build.make tests/calc/tetra-h1-newton/CMakeFiles/calc-tetra-h1-newton.dir/build
.PHONY : calc-tetra-h1-newton/fast

#=============================================================================
# Target rules for targets named calc-hex-h1

# Build rule for target.
calc-hex-h1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1
.PHONY : calc-hex-h1

# fast build rule for target.
calc-hex-h1/fast:
	$(MAKE) -f tests/calc/hex-h1/CMakeFiles/calc-hex-h1.dir/build.make tests/calc/hex-h1/CMakeFiles/calc-hex-h1.dir/build
.PHONY : calc-hex-h1/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-dirichlet

# Build rule for target.
calc-hex-h1-dirichlet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-dirichlet
.PHONY : calc-hex-h1-dirichlet

# fast build rule for target.
calc-hex-h1-dirichlet/fast:
	$(MAKE) -f tests/calc/hex-h1-dirichlet/CMakeFiles/calc-hex-h1-dirichlet.dir/build.make tests/calc/hex-h1-dirichlet/CMakeFiles/calc-hex-h1-dirichlet.dir/build
.PHONY : calc-hex-h1-dirichlet/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-neumann

# Build rule for target.
calc-hex-h1-neumann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-neumann
.PHONY : calc-hex-h1-neumann

# fast build rule for target.
calc-hex-h1-neumann/fast:
	$(MAKE) -f tests/calc/hex-h1-neumann/CMakeFiles/calc-hex-h1-neumann.dir/build.make tests/calc/hex-h1-neumann/CMakeFiles/calc-hex-h1-neumann.dir/build
.PHONY : calc-hex-h1-neumann/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-newton

# Build rule for target.
calc-hex-h1-newton: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-newton
.PHONY : calc-hex-h1-newton

# fast build rule for target.
calc-hex-h1-newton/fast:
	$(MAKE) -f tests/calc/hex-h1-newton/CMakeFiles/calc-hex-h1-newton.dir/build.make tests/calc/hex-h1-newton/CMakeFiles/calc-hex-h1-newton.dir/build
.PHONY : calc-hex-h1-newton/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-unsym

# Build rule for target.
calc-hex-h1-unsym: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-unsym
.PHONY : calc-hex-h1-unsym

# fast build rule for target.
calc-hex-h1-unsym/fast:
	$(MAKE) -f tests/calc/hex-h1-unsym/CMakeFiles/calc-hex-h1-unsym.dir/build.make tests/calc/hex-h1-unsym/CMakeFiles/calc-hex-h1-unsym.dir/build
.PHONY : calc-hex-h1-unsym/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-sys

# Build rule for target.
calc-hex-h1-sys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-sys
.PHONY : calc-hex-h1-sys

# fast build rule for target.
calc-hex-h1-sys/fast:
	$(MAKE) -f tests/calc/hex-h1-sys/CMakeFiles/calc-hex-h1-sys.dir/build.make tests/calc/hex-h1-sys/CMakeFiles/calc-hex-h1-sys.dir/build
.PHONY : calc-hex-h1-sys/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-sys-dirichlet

# Build rule for target.
calc-hex-h1-sys-dirichlet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-sys-dirichlet
.PHONY : calc-hex-h1-sys-dirichlet

# fast build rule for target.
calc-hex-h1-sys-dirichlet/fast:
	$(MAKE) -f tests/calc/hex-h1-sys-dirichlet/CMakeFiles/calc-hex-h1-sys-dirichlet.dir/build.make tests/calc/hex-h1-sys-dirichlet/CMakeFiles/calc-hex-h1-sys-dirichlet.dir/build
.PHONY : calc-hex-h1-sys-dirichlet/fast

#=============================================================================
# Target rules for targets named calc-hex-h1-sys-coupled

# Build rule for target.
calc-hex-h1-sys-coupled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-h1-sys-coupled
.PHONY : calc-hex-h1-sys-coupled

# fast build rule for target.
calc-hex-h1-sys-coupled/fast:
	$(MAKE) -f tests/calc/hex-h1-sys-coupled/CMakeFiles/calc-hex-h1-sys-coupled.dir/build.make tests/calc/hex-h1-sys-coupled/CMakeFiles/calc-hex-h1-sys-coupled.dir/build
.PHONY : calc-hex-h1-sys-coupled/fast

#=============================================================================
# Target rules for targets named calc-hex-hcurl

# Build rule for target.
calc-hex-hcurl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-hcurl
.PHONY : calc-hex-hcurl

# fast build rule for target.
calc-hex-hcurl/fast:
	$(MAKE) -f tests/calc/hex-hcurl/CMakeFiles/calc-hex-hcurl.dir/build.make tests/calc/hex-hcurl/CMakeFiles/calc-hex-hcurl.dir/build
.PHONY : calc-hex-hcurl/fast

#=============================================================================
<<<<<<< HEAD
# Target rules for targets named calc-hex-hcurl-cplx

# Build rule for target.
calc-hex-hcurl-cplx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-hcurl-cplx
.PHONY : calc-hex-hcurl-cplx

# fast build rule for target.
calc-hex-hcurl-cplx/fast:
	$(MAKE) -f tests/calc/hex-hcurl-cplx/CMakeFiles/calc-hex-hcurl-cplx.dir/build.make tests/calc/hex-hcurl-cplx/CMakeFiles/calc-hex-hcurl-cplx.dir/build
.PHONY : calc-hex-hcurl-cplx/fast

#=============================================================================
# Target rules for targets named calc-hex-hcurl-imped

# Build rule for target.
calc-hex-hcurl-imped: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calc-hex-hcurl-imped
.PHONY : calc-hex-hcurl-imped

# fast build rule for target.
calc-hex-hcurl-imped/fast:
	$(MAKE) -f tests/calc/hex-hcurl-imped/CMakeFiles/calc-hex-hcurl-imped.dir/build.make tests/calc/hex-hcurl-imped/CMakeFiles/calc-hex-hcurl-imped.dir/build
.PHONY : calc-hex-hcurl-imped/fast

#=============================================================================
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
# Target rules for targets named hnnd-hex-h1-dirichlet

# Build rule for target.
hnnd-hex-h1-dirichlet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hnnd-hex-h1-dirichlet
.PHONY : hnnd-hex-h1-dirichlet

# fast build rule for target.
hnnd-hex-h1-dirichlet/fast:
	$(MAKE) -f tests/hang-nodes/hex-h1/CMakeFiles/hnnd-hex-h1-dirichlet.dir/build.make tests/hang-nodes/hex-h1/CMakeFiles/hnnd-hex-h1-dirichlet.dir/build
.PHONY : hnnd-hex-h1-dirichlet/fast

#=============================================================================
# Target rules for targets named hnnd-hex-h1-newton

# Build rule for target.
hnnd-hex-h1-newton: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hnnd-hex-h1-newton
.PHONY : hnnd-hex-h1-newton

# fast build rule for target.
hnnd-hex-h1-newton/fast:
	$(MAKE) -f tests/hang-nodes/hex-h1/CMakeFiles/hnnd-hex-h1-newton.dir/build.make tests/hang-nodes/hex-h1/CMakeFiles/hnnd-hex-h1-newton.dir/build
.PHONY : hnnd-hex-h1-newton/fast

#=============================================================================
# Target rules for targets named hnnd-hex-hcurl

# Build rule for target.
hnnd-hex-hcurl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hnnd-hex-hcurl
.PHONY : hnnd-hex-hcurl

# fast build rule for target.
hnnd-hex-hcurl/fast:
	$(MAKE) -f tests/hang-nodes/hex-hcurl/CMakeFiles/hnnd-hex-hcurl.dir/build.make tests/hang-nodes/hex-hcurl/CMakeFiles/hnnd-hex-hcurl.dir/build
.PHONY : hnnd-hex-hcurl/fast

#=============================================================================
# Target rules for targets named judy-templates

# Build rule for target.
judy-templates: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 judy-templates
.PHONY : judy-templates

# fast build rule for target.
judy-templates/fast:
	$(MAKE) -f tests/judy-templates/CMakeFiles/judy-templates.dir/build.make tests/judy-templates/CMakeFiles/judy-templates.dir/build
.PHONY : judy-templates/fast

#=============================================================================
# Target rules for targets named solver

# Build rule for target.
solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver
.PHONY : solver

# fast build rule for target.
solver/fast:
	$(MAKE) -f tests/linear-solvers/CMakeFiles/solver.dir/build.make tests/linear-solvers/CMakeFiles/solver.dir/build
.PHONY : solver/fast

#=============================================================================
<<<<<<< HEAD
# Target rules for targets named solver-cplx

# Build rule for target.
solver-cplx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver-cplx
.PHONY : solver-cplx

# fast build rule for target.
solver-cplx/fast:
	$(MAKE) -f tests/linear-solvers/CMakeFiles/solver-cplx.dir/build.make tests/linear-solvers/CMakeFiles/solver-cplx.dir/build
.PHONY : solver-cplx/fast

#=============================================================================
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
# Target rules for targets named mesh-copy

# Build rule for target.
mesh-copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mesh-copy
.PHONY : mesh-copy

# fast build rule for target.
mesh-copy/fast:
	$(MAKE) -f tests/mesh/copy/CMakeFiles/mesh-copy.dir/build.make tests/mesh/copy/CMakeFiles/mesh-copy.dir/build
.PHONY : mesh-copy/fast

#=============================================================================
# Target rules for targets named mesh-refinements

# Build rule for target.
mesh-refinements: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mesh-refinements
.PHONY : mesh-refinements

# fast build rule for target.
mesh-refinements/fast:
	$(MAKE) -f tests/mesh/refinements/CMakeFiles/mesh-refinements.dir/build.make tests/mesh/refinements/CMakeFiles/mesh-refinements.dir/build
.PHONY : mesh-refinements/fast

#=============================================================================
# Target rules for targets named regularize

# Build rule for target.
regularize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regularize
.PHONY : regularize

# fast build rule for target.
regularize/fast:
	$(MAKE) -f tests/mesh/regularize/CMakeFiles/regularize.dir/build.make tests/mesh/regularize/CMakeFiles/regularize.dir/build
.PHONY : regularize/fast

#=============================================================================
# Target rules for targets named multi-mesh-rhs2

# Build rule for target.
multi-mesh-rhs2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi-mesh-rhs2
.PHONY : multi-mesh-rhs2

# fast build rule for target.
multi-mesh-rhs2/fast:
	$(MAKE) -f tests/mesh/multi-mesh/CMakeFiles/multi-mesh-rhs2.dir/build.make tests/mesh/multi-mesh/CMakeFiles/multi-mesh-rhs2.dir/build
.PHONY : multi-mesh-rhs2/fast

#=============================================================================
# Target rules for targets named multi-mesh-sys3

# Build rule for target.
multi-mesh-sys3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi-mesh-sys3
.PHONY : multi-mesh-sys3

# fast build rule for target.
multi-mesh-sys3/fast:
	$(MAKE) -f tests/mesh/multi-mesh/CMakeFiles/multi-mesh-sys3.dir/build.make tests/mesh/multi-mesh/CMakeFiles/multi-mesh-sys3.dir/build
.PHONY : multi-mesh-sys3/fast

#=============================================================================
# Target rules for targets named mesh-loader

# Build rule for target.
mesh-loader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mesh-loader
.PHONY : mesh-loader

# fast build rule for target.
mesh-loader/fast:
	$(MAKE) -f tests/mesh-loaders/CMakeFiles/mesh-loader.dir/build.make tests/mesh-loaders/CMakeFiles/mesh-loader.dir/build
.PHONY : mesh-loader/fast

#=============================================================================
# Target rules for targets named orders

# Build rule for target.
orders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orders
.PHONY : orders

# fast build rule for target.
orders/fast:
	$(MAKE) -f tests/orders/CMakeFiles/orders.dir/build.make tests/orders/CMakeFiles/orders.dir/build
.PHONY : orders/fast

#=============================================================================
# Target rules for targets named output-gmsh

# Build rule for target.
output-gmsh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output-gmsh
.PHONY : output-gmsh

# fast build rule for target.
output-gmsh/fast:
	$(MAKE) -f tests/output/CMakeFiles/output-gmsh.dir/build.make tests/output/CMakeFiles/output-gmsh.dir/build
.PHONY : output-gmsh/fast

#=============================================================================
# Target rules for targets named output-vtk

# Build rule for target.
output-vtk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output-vtk
.PHONY : output-vtk

# fast build rule for target.
output-vtk/fast:
	$(MAKE) -f tests/output/CMakeFiles/output-vtk.dir/build.make tests/output/CMakeFiles/output-vtk.dir/build
.PHONY : output-vtk/fast

#=============================================================================
# Target rules for targets named quadrature

# Build rule for target.
quadrature: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quadrature
.PHONY : quadrature

# fast build rule for target.
quadrature/fast:
	$(MAKE) -f tests/quadrature/CMakeFiles/quadrature.dir/build.make tests/quadrature/CMakeFiles/quadrature.dir/build
.PHONY : quadrature/fast

#=============================================================================
# Target rules for targets named timer

# Build rule for target.
timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timer
.PHONY : timer

# fast build rule for target.
timer/fast:
	$(MAKE) -f tests/timer/CMakeFiles/timer.dir/build.make tests/timer/CMakeFiles/timer.dir/build
.PHONY : timer/fast

#=============================================================================
# Target rules for targets named elastostatics

# Build rule for target.
elastostatics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elastostatics
.PHONY : elastostatics

# fast build rule for target.
elastostatics/fast:
	$(MAKE) -f examples/elastostatics/CMakeFiles/elastostatics.dir/build.make examples/elastostatics/CMakeFiles/elastostatics.dir/build
.PHONY : elastostatics/fast

#=============================================================================
<<<<<<< HEAD
=======
# Target rules for targets named fichera

# Build rule for target.
fichera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fichera
.PHONY : fichera

# fast build rule for target.
fichera/fast:
	$(MAKE) -f examples/fichera/CMakeFiles/fichera.dir/build.make examples/fichera/CMakeFiles/fichera.dir/build
.PHONY : fichera/fast

#=============================================================================
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
# Target rules for targets named heat-conduction

# Build rule for target.
heat-conduction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heat-conduction
.PHONY : heat-conduction

# fast build rule for target.
heat-conduction/fast:
	$(MAKE) -f examples/heat-conduction/CMakeFiles/heat-conduction.dir/build.make examples/heat-conduction/CMakeFiles/heat-conduction.dir/build
.PHONY : heat-conduction/fast

#=============================================================================
# Target rules for targets named singpert-aniso

# Build rule for target.
singpert-aniso: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 singpert-aniso
.PHONY : singpert-aniso

# fast build rule for target.
singpert-aniso/fast:
	$(MAKE) -f examples/singpert-aniso/CMakeFiles/singpert-aniso.dir/build.make examples/singpert-aniso/CMakeFiles/singpert-aniso.dir/build
.PHONY : singpert-aniso/fast

#=============================================================================
<<<<<<< HEAD
# Target rules for targets named fichera

# Build rule for target.
fichera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fichera
.PHONY : fichera

# fast build rule for target.
fichera/fast:
	$(MAKE) -f benchmarks/fichera/CMakeFiles/fichera.dir/build.make benchmarks/fichera/CMakeFiles/fichera.dir/build
.PHONY : fichera/fast

#=============================================================================
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
# Target rules for targets named layer

# Build rule for target.
layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 layer
.PHONY : layer

# fast build rule for target.
layer/fast:
	$(MAKE) -f benchmarks/layer/CMakeFiles/layer.dir/build.make benchmarks/layer/CMakeFiles/layer.dir/build
.PHONY : layer/fast

<<<<<<< HEAD
#=============================================================================
# Target rules for targets named bessel

# Build rule for target.
bessel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bessel
.PHONY : bessel

# fast build rule for target.
bessel/fast:
	$(MAKE) -f benchmarks/bessel/CMakeFiles/bessel.dir/build.make benchmarks/bessel/CMakeFiles/bessel.dir/build
.PHONY : bessel/fast

=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... benchmarks"
	@echo "... edit_cache"
	@echo "... examples"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test-quick"
<<<<<<< HEAD
	@echo "... hermes3d-cplx-debug"
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
	@echo "... hermes3d-debug"
	@echo "... adapt-h1-simple"
	@echo "... projection"
	@echo "... adapt-smooth"
	@echo "... calc-tetra-h1"
	@echo "... calc-tetra-h1-dirichlet"
	@echo "... calc-tetra-h1-neumann"
	@echo "... calc-tetra-h1-newton"
	@echo "... calc-hex-h1"
	@echo "... calc-hex-h1-dirichlet"
	@echo "... calc-hex-h1-neumann"
	@echo "... calc-hex-h1-newton"
	@echo "... calc-hex-h1-unsym"
	@echo "... calc-hex-h1-sys"
	@echo "... calc-hex-h1-sys-dirichlet"
	@echo "... calc-hex-h1-sys-coupled"
	@echo "... calc-hex-hcurl"
<<<<<<< HEAD
	@echo "... calc-hex-hcurl-cplx"
	@echo "... calc-hex-hcurl-imped"
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
	@echo "... hnnd-hex-h1-dirichlet"
	@echo "... hnnd-hex-h1-newton"
	@echo "... hnnd-hex-hcurl"
	@echo "... judy-templates"
	@echo "... solver"
<<<<<<< HEAD
	@echo "... solver-cplx"
=======
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
	@echo "... mesh-copy"
	@echo "... mesh-refinements"
	@echo "... regularize"
	@echo "... multi-mesh-rhs2"
	@echo "... multi-mesh-sys3"
	@echo "... mesh-loader"
	@echo "... orders"
	@echo "... output-gmsh"
	@echo "... output-vtk"
	@echo "... quadrature"
	@echo "... timer"
	@echo "... elastostatics"
<<<<<<< HEAD
	@echo "... heat-conduction"
	@echo "... singpert-aniso"
	@echo "... fichera"
	@echo "... layer"
	@echo "... bessel"
=======
	@echo "... fichera"
	@echo "... heat-conduction"
	@echo "... singpert-aniso"
	@echo "... layer"
>>>>>>> 7b4a514fa10cb5c19abd7f0a921f69407b9ba3ad
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

